resources:
  - name: my-source-code
    type: git
    source:
      uri: https://github.com/Trezeguet-tech/api-calculate.git
      branch: main

  - name: my-gradle-repo
    type: artifactory
    source:
      url: https://tkwebtech.jfrog.io/artifactory/gradle/gradle-local
      username: kadt2022@gmail.com
      password: cmVmdGtuOjAxOjE3Mzk4MzI0MzM6ZmxTbkNRbmFRZTZ6ZEVaREZ2MlhmZnRBSW9W
      repository: gradle-local
      package_type: gradle

jobs:
  - name: build-and-publish
    plan:
      - get: my-source-code
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: '3.8.4-openjdk-17'
          inputs:
            - name: my-source-code
          outputs:
            - name: build-output
          run:
            path: /bin/sh
            args:
              - -exc
              - |
                cd my-source-code
                ./gradlew clean assemble
                mv build/libs/*.jar ../build-output/
      - put: my-gradle-repo
        params:
          file: build-output/*.jar
